-- Create sound_generations table for AI sound generation tracking
CREATE TABLE IF NOT EXISTS sound_generations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  job_id TEXT UNIQUE,
  prompt TEXT NOT NULL,
  title TEXT,
  duration_seconds NUMERIC NOT NULL CHECK (duration_seconds >= 1 AND duration_seconds <= 22),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  output_audio_url TEXT,
  error_message TEXT,
  webhook_status TEXT CHECK (webhook_status IN ('pending', 'delivered', 'failed')),
  webhook_delivered_at TIMESTAMPTZ,
  fal_request_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX idx_sound_generations_user_id ON sound_generations(user_id);
CREATE INDEX idx_sound_generations_job_id ON sound_generations(job_id);
CREATE INDEX idx_sound_generations_status ON sound_generations(status);
CREATE INDEX idx_sound_generations_created_at ON sound_generations(created_at DESC);

-- Enable RLS
ALTER TABLE sound_generations ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own sound generations"
  ON sound_generations FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own sound generations"
  ON sound_generations FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Only service role can update (for webhook handling)
CREATE POLICY "Service role can update all sound generations"
  ON sound_generations FOR UPDATE
  USING (auth.role() = 'service_role');

-- Add comment to the table
COMMENT ON TABLE sound_generations IS 'Tracks AI sound generation jobs using fal.ai ElevenLabs API';
COMMENT ON COLUMN sound_generations.job_id IS 'Unique job ID for tracking async sound generation';
COMMENT ON COLUMN sound_generations.prompt IS 'User input describing the sound effect to generate';
COMMENT ON COLUMN sound_generations.duration_seconds IS 'Duration of the sound effect in seconds (1-22)';
COMMENT ON COLUMN sound_generations.webhook_status IS 'Status of webhook delivery from fal.ai';
COMMENT ON COLUMN sound_generations.fal_request_id IS 'Request ID returned by fal.ai for tracking';